server:
  port: 8083
  
spring:
  cloud:
    stream:
      kafka:
        bindings:
          ClassCustomerEvent:
            producer:
              sync: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
