spring:
  data:
    mongodb:
      host: 192.168.99.1
      database: School
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.1
          zkNodes: 192.168.99.1

school:
  classcustomer:
    eventsourcing:
      processor:
        limitForReading: 50
        lockedMessageMaxTimeInMinutes: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-school:8761/eureka/
