spring:
  data:
    mongodb:
      host: localhost
      database: School
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost

school:
  classcustomer:
    eventsourcing:
      processor:
        limitForReading: 50
        lockedMessageMaxTimeInMinutes: 1

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/